import { BottomTabsItem } from '../common/bean/BottomTabsItem'
export const BottomTabsDatas:Array<BottomTabsItem>=[
  {
    icon:$r('app.media.ic_home_normal'),
    iconSelected:$r('app.media.ic_home_selected'),
    text:$r('app.string.bottom_text_home')
  },
  {
    icon:$r('app.media.ic_nav_normal'),
    iconSelected:$r('app.media.ic_nav_selected'),
    text:$r('app.string.bottom_text_nav')
  },
  {
    icon:$r('app.media.ic_project_normal'),
    iconSelected:$r('app.media.ic_project_selected'),
    text:$r('app.string.bottom_text_project')
  },
  {
    icon:$r('app.media.ic_msg_normal'),
    iconSelected:$r('app.media.ic_msg_selected'),
    text:$r('app.string.bottom_text_msg')
  },
  {
    icon:$r('app.media.ic_mine_normal'),
    iconSelected:$r('app.media.ic_mine_selected'),
    text:$r('app.string.bottom_text_mine')
  },
]